[project]
name = "eConEXG"
dynamic = ["version"]
authors = [{ name = "Alex You", email = "yoyialex@outlook.com" }]

description = "Add your description here"
dependencies = [
    "numpy",
    "pyserial>=3.5",
    "pyEDFlib>=0.1.37",
    "pylsl>=1.16.2",
    "netifaces;platform_system=='Windows'",
    "netifaces;platform_system=='Darwin'",
    "netifaces2;platform_system=='Linux'",
    "pywifi>=1.1.12;platform_system=='Windows'",
    "comtypes;platform_system=='Windows'",
]
readme = "README.md"
requires-python = ">= 3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[tool.hatch.version]
path = "src/eConEXG/version.py"
[project.urls]
Homepage = "https://github.com/Niantong-Intelligence/eConEXG"
Issues = "https://github.com/Niantong-Intelligence/eConEXG/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["pytest>=8.1.1"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
only-include = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/eConEXG"]
artifacts= [
    "*.so",
    "*.pyd",
    "*.dll",
    "*.dylib",
]

[tool.hatch.publish.index]
disable = true
